# Generated by Django 3.2.6 on 2021-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=123456789, max_length=15),
        ),
    ]
